/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import javax.swing.ImageIcon;
import sistema.SistemaEnviaPack;
import javax.swing.table.DefaultTableModel;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import modelo.GuiaEnvio;
import modelo.Paquete;
import sistema.SistemaEnviaPack;

/**
 *
 * @author soloa
 */
public class PanelGuias extends javax.swing.JFrame {
    private SistemaEnviaPack sistema;
    private int numeroGuiaAuto = 1;
    /**
     * Creates new form PanelGuias
     */
    
   public void cargarComboPaquetes() {
    cmbPaquetes.removeAllItems();
    cargarComboDesdeArbol(sistema.getArbolDestinos().getRaiz());
}
   

private void cargarComboDesdeArbol(estructuras.NodoArbol nodo) {
    if (nodo != null) {
        cargarComboDesdeArbol(nodo.getEnlaceIzq());

        for (int i = 0; i < nodo.getPaquetes().cantidad(); i++) {
            Paquete p = nodo.getPaquetes().obtenerPorPosicion(i);
            cmbPaquetes.addItem(nodo.getDestino() + " - " + p.getCodigo() + " - " + p.getDescripcion());
        }

        cargarComboDesdeArbol(nodo.getEnlaceDer());
    }
}
    public void mostrarTablaGuias() {
    DefaultTableModel modeloTabla = (DefaultTableModel) tblGuias.getModel();
    modeloTabla.setRowCount(0);

    for (int i = 0; i < sistema.getListaGuias().cantidad(); i++) {
        GuiaEnvio g = sistema.getListaGuias().obtenerPorPosicion(i);

        Object fila[] = new Object[6];
        fila[0] = g.getNumeroGuia();
        fila[1] = g.getDescripcion();
        fila[2] = g.getTipoEnvio();
        fila[3] = g.getCodigoSeguimiento();
        fila[4] = g.getCiudadDestino();
        fila[5] = g.getFechaGeneracion();

        modeloTabla.addRow(fila);
    }
    
    

    jLabel2.setText(String.valueOf(sistema.getListaGuias().cantidad()));
}
    public Paquete buscarPaquetePorCodigo(int codigo) {
    for (int i = 0; i < sistema.getLista().cantidad(); i++) {
        Paquete p = sistema.getLista().obtenerPorPosicion(i);

        if (p.getCodigo() == codigo) {
            return p;
        }
    }
    return null;
}

public Paquete buscarPaqueteEnArbolPorCodigo(estructuras.NodoArbol nodo, int codigo) {
    if (nodo == null) {
        return null;
    }

    for (int i = 0; i < nodo.getPaquetes().cantidad(); i++) {
        Paquete p = nodo.getPaquetes().obtenerPorPosicion(i);
        if (p.getCodigo() == codigo) {
            return p;
        }
    }

    Paquete encontradoIzq = buscarPaqueteEnArbolPorCodigo(nodo.getEnlaceIzq(), codigo);
    if (encontradoIzq != null) {
        return encontradoIzq;
    }

    return buscarPaqueteEnArbolPorCodigo(nodo.getEnlaceDer(), codigo);
}

public String buscarDestinoDePaquete(estructuras.NodoArbol nodo, int codigo) {
    if (nodo == null) {
        return "";
    }

    for (int i = 0; i < nodo.getPaquetes().cantidad(); i++) {
        Paquete p = nodo.getPaquetes().obtenerPorPosicion(i);
        if (p.getCodigo() == codigo) {
            return nodo.getDestino();
        }
    }

    String destinoIzq = buscarDestinoDePaquete(nodo.getEnlaceIzq(), codigo);
    if (!destinoIzq.equals("")) {
        return destinoIzq;
    }

    return buscarDestinoDePaquete(nodo.getEnlaceDer(), codigo);
} 
    
    
    public PanelGuias(SistemaEnviaPack sistema) {
        initComponents();
        this.sistema = sistema;
         setIconImage(new ImageIcon(getClass().getResource("/img/icono_ventana_64.png")).getImage());
         
         DefaultTableModel modeloTabla = (DefaultTableModel) tblGuias.getModel();
         modeloTabla.setRowCount(0);

         cargarComboPaquetes();
         mostrarTablaGuias();
        
         
            //para el color de columnas y filas de la tabla jtlPquetes
        javax.swing.table.JTableHeader header = tblGuias.getTableHeader();
        header.setDefaultRenderer(new javax.swing.table.DefaultTableCellRenderer() {
       @Override
       public java.awt.Component getTableCellRendererComponent(javax.swing.JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
           super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
           setBackground(new java.awt.Color(11, 29, 58));
           setForeground(java.awt.Color.WHITE);
           setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 12));
           setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
           setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 1, new java.awt.Color(26, 58, 92)));
           return this;
    }
       
});
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cmbPaquetes = new javax.swing.JComboBox<>();
        btnGenararGuia = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblGuias = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        btnVolverMenu = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(11, 29, 58));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Generación de Guías de Envío");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(107, 114, 128));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Guías almacenadas en una Lista");

        jPanel2.setBackground(new java.awt.Color(220, 223, 228));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(11, 29, 58));
        jLabel5.setText("Generar Nueva Guía");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(107, 114, 128));
        jLabel6.setText("Seleccionar paquete clasificado");

        cmbPaquetes.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        cmbPaquetes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnGenararGuia.setBackground(new java.awt.Color(245, 166, 35));
        btnGenararGuia.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        btnGenararGuia.setForeground(new java.awt.Color(11, 29, 58));
        btnGenararGuia.setText("Generar Guía ");
        btnGenararGuia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenararGuiaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(cmbPaquetes, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                        .addComponent(btnGenararGuia, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cmbPaquetes, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGenararGuia, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(220, 223, 228));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(11, 29, 58));
        jLabel7.setText("Consultar Guías");

        txtBuscar.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N

        btnBuscar.setBackground(new java.awt.Color(11, 29, 58));
        btnBuscar.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(107, 114, 128));
        jLabel8.setText("Buscar por código de seguimiento");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        tblGuias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                " N° Guía", "Descripción", "Tipo Envío", "Cód. Seguimiento", "Ciudad Destino", "Fecha Generación"
            }
        ));
        jScrollPane1.setViewportView(tblGuias);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo_menu.png"))); // NOI18N

        btnVolverMenu.setBackground(new java.awt.Color(11, 29, 58));
        btnVolverMenu.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnVolverMenu.setForeground(new java.awt.Color(255, 255, 255));
        btnVolverMenu.setText("Volver al Menú");
        btnVolverMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverMenuActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(11, 29, 58));
        jLabel9.setText("Guías Generadas (Lista)");

        jLabel2.setText("num guias");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnVolverMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(306, 306, 306)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(360, 360, 360)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnVolverMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 794, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverMenuActionPerformed
        PanelMenu m = new PanelMenu(sistema);
        m.setVisible(true);
        m.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnVolverMenuActionPerformed

    private void btnGenararGuiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenararGuiaActionPerformed
if (cmbPaquetes.getSelectedItem() == null) {
    JOptionPane.showMessageDialog(null, "No hay paquetes clasificados");
    return;
}

String seleccionado = cmbPaquetes.getSelectedItem().toString();
String partes[] = seleccionado.split(" - ");
int codigoPaquete = Integer.parseInt(partes[1]);

Paquete p = buscarPaqueteEnArbolPorCodigo(sistema.getArbolDestinos().getRaiz(), codigoPaquete);
String destino = buscarDestinoDePaquete(sistema.getArbolDestinos().getRaiz(), codigoPaquete);

if (p == null) {
    JOptionPane.showMessageDialog(null, "No se encontró el paquete");
    return;
}

GuiaEnvio guia = new GuiaEnvio();
guia.setNumeroGuia(numeroGuiaAuto);
guia.setDescripcion(p.getDescripcion());
guia.setTipoEnvio(p.getTipoEnvio());
guia.setCodigoSeguimiento("SEG-" + p.getCodigo() + "-" + numeroGuiaAuto);
guia.setCiudadDestino(destino);
guia.setFechaGeneracion(LocalDate.now().toString());

sistema.getListaGuias().insertar(guia);
numeroGuiaAuto++;

mostrarTablaGuias();

JOptionPane.showMessageDialog(null, "Guía generada correctamente");
    // TODO add your handling code here:
    }//GEN-LAST:event_btnGenararGuiaActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        if (txtBuscar.getText().equals("")) {
        JOptionPane.showMessageDialog(null, "Digite el código de seguimiento");
        txtBuscar.requestFocus();
        return;
    }

    GuiaEnvio g = sistema.getListaGuias().buscarPorCodigoSeguimiento(txtBuscar.getText());

    if (g != null) {
        JOptionPane.showMessageDialog(null,
                "Guía encontrada\n\n"
                + "N° Guía: " + g.getNumeroGuia()
                + "\nDescripción: " + g.getDescripcion()
                + "\nTipo Envío: " + g.getTipoEnvio()
                + "\nCódigo Seguimiento: " + g.getCodigoSeguimiento()
                + "\nCiudad Destino: " + g.getCiudadDestino()
                + "\nFecha Generación: " + g.getFechaGeneracion());
    } else {
        JOptionPane.showMessageDialog(null, "No se encontró la guía");
    }
    }//GEN-LAST:event_btnBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelGuias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelGuias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelGuias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelGuias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelGuias(new SistemaEnviaPack()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnGenararGuia;
    private javax.swing.JButton btnVolverMenu;
    private javax.swing.JComboBox<String> cmbPaquetes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblGuias;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
